### ISSUE TITLE
Yandex Map Api Key exposed in the source code

### ISSUE THREAD

**Issue by sergous** [dtpstat/website#108]
Better to clean it up in case of publish the code.

https://github.com/dtpstat/website/blob/b7a76dd946e09442550d00f0792047edc1505a2f/src/pages/iframes/map.tsx#L20

**Comment by PiRomant** [comment]
Так он же на фронте в открытом виде. И его использование ограниченно определенными доменами
![image](https://user-images.githubusercontent.com/29551044/217543861-4ad604d3-621c-4cd1-9074-835b13f10138.png)

**Comment by alexander-mart** [comment]
## Рекомендации по работе с API Яндекс.Карт

### 1. Ограничьте использование токена
Яндекс позволяет устанавливать ограничение использования API-токенов по домену. Это обязательная мера в случае, если API вызывается из браузера.  
Зайдите в кабинет управления API Яндекс (https://developer.tech.yandex.ru/) и настройте ограничение так, чтобы токен можно было использовать только с вашего доменного имени (например, example.com).

#### Пример настройки:
- Перейдите в проект, где создан API-токен.
- Укажите в разделе настроек безопасный домен (или несколько доменов), с которых разрешены запросы.

### 2. Избегайте явного хранения токена в коде
Даже если вы ограничили домены, это не гарантирует полной безопасности. Поэтому токен желательно скрывать на серверной стороне.

#### Пример реализации:
- Создайте промежуточное API на своём сервере (прокси). Клиент запрашивает данные у вашего сервера, а тот — добавляет токен и обращается к Яндекс API.  
  Это исключит возможность прямого копирования токена.

#### Пример кода:
```tsx
// На клиенте: запрос к собственному API
fetch('/api/maps-data')
  .then(response => response.json())
  .then(data => console.log(data));

// На сервере (Node.js в Express)
app.get('/api/maps-data', async (req, res) => {
  const yandexApiUrl = `https://api-maps.yandex.ru/2.1/?apikey=${process.env.YANDEX_API_KEY}&lang=ru_RU&coordorder=longlat`;
  const response = await fetch(yandexApiUrl);
  const data = await response.json();
  res.json(data);
});
```

**Comment by alexander-mart** [comment]
Documentation:
https://yandex.ru/dev/jsapi30/doc/ru/common/quickstart.html
