### ISSUE TITLE
Auth0 создать продакшн аккаунт

### ISSUE THREAD

**Issue by alexander-mart** [dtpstat/website#19]

**Comment by sergous** [comment]
поскольку настроена двуфакторная авторизация, мы не можем пользоваться твоей учеткой. 
Добавь нас админами вот тут показано где:
<img width="1606" alt="auth0-invite-members" src="https://user-images.githubusercontent.com/545151/151722962-ab02fd16-1700-4075-87c0-942047653d2f.png">

**Comment by alexander-mart** [comment]
Auth0 production почти настроен. Если будет ещё актуально, добавлю доступы, кто сделает запрос.
