### ISSUE TITLE
Не работает отправка комментариев. При нажатии кнопки «Отправить» она мигает и всё

### ISSUE THREAD

**Issue by alexander-mart** [dtpstat/website#26]
- Залогинился через Google аккаунт.
- После нажатия «Отправить» в консоли: `POST https://dtp-stat-on-nextjs.netlify.app/api/comments 500`

**Comment by sergous** [comment]
проблема в том, что версия бд была настроена на новые фичи, которые находились в ревью и не были залиты в ветку main. после получения апрува я залил новые фичи и проблема разрешилась.

чтобы это не возникало нужно подключить прод бд https://github.com/dtpstat/dtp-stat/issues/57
