### ISSUE TITLE
Prisma can't find DATABASE_URL in .env.local

### ISSUE THREAD

**Issue by sergous** [dtpstat/website#47]
For prisma console operations, prisma checks in .env file, but not .env.local

```
sergous@sMacBookPro15 website % yarn prisma db push
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get config: Schema Parsing P1012

error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
```

**Comment by kachkaev** [comment]
Looks like Prisma does not read multiple `.env` files by default. They describe what to do in their docs though:
https://www.prisma.io/docs/guides/development-environment/environment-variables/using-multiple-env-files

Alternatively, we can use [`dotenv-flow`](https://www.npmjs.com/package/dotenv-flow), also via `package.json`. Something like:

```json
{
  "scripts": {
     "...": "...",
     "prisma": "node -r dotenv-flow/config ./node_modules/.bin/prisma",
     "...": "..."
   }
}
```

Commands to run should not change.

**Comment by sergous** [comment]
> 

That is works, thanks. Send you RP for approval.
